language: php

# faster builds on docker-container setup
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly

branches:
    only:
        - v2

install:
    - composer self-update

# build coverage only on one build, to speed up results feedbacks
before_script:
    - php -i | grep max_execution_time
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then PHPUNIT_FLAGS="-d max_execution_time=0 --coverage-clover=coverage.clover"; else PHPUNIT_FLAGS=""; fi;
    - php -i | grep max_execution_time

script:
    - ant prepare
    - phpunit --exclude-group command-doctrine --debug $PHPUNIT_FLAGS

after_script:
    - |
        if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
        if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi
