wallabag_api:
    resource: @WallabagApiBundle/Controller
    prefix:   annotation

wallabag_core:
    resource: @WallabagCoreBundle/Controller/
    type:     annotation

homepage:
    pattern:   /
    defaults:  { _controller: WallabagCoreBundle:Entry:showUnread }

doc-api:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

login:
    pattern:   /login
    defaults:  { _controller: WallabagCoreBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    path:   /logout

rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api
